

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]


  - job_name: "node-app"
    scrape_interval: 10s
    static_configs:
      - targets: ["nestjs-app:3000"]

